Models/Hàng_Hóa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hàng_Hóa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hàng_Hóa()
        {
            this.Chi_tiết_hóa_đơn = new HashSet<Chi_tiết_hóa_đơn>();
        }
    
        public int ID { get; set; }
        public string Tên { get; set; }
        public int Giá_mua { get; set; }
        public int Giá_bán { get; set; }
        public string ID_loại { get; set; }
        public string ID_DVT { get; set; }
        public Nullable<int> SL_ton { get; set; }
        public string Hinh_anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiết_hóa_đơn> Chi_tiết_hóa_đơn { get; set; }
        public virtual ĐVT ĐVT { get; set; }
        public virtual Loại Loại { get; set; }
    }
}

Controllers/Hàng_HóaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.IO;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Demo_CNPM.Models;
using System.Web.Security;
using Demo_CNPM.App_Start;

namespace Demo_CNPM.Controllers
{
    public class Hàng_HóaController : Controller
    {
        private taphoa_final_demoEntities4 db = new taphoa_final_demoEntities4();



        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(string user, int password)
        {
            //check DB
            var nhanVien = db.Nhân_viên.SingleOrDefault(m => m.ID == user && m.Password == password);

            if (nhanVien != null)
            {
                Session["user"] = nhanVien;
                ViewBag.user = nhanVien;
                TempData["error"] = new Nhân_viên();

                return RedirectToAction("Proview");
            }

            else
            {
                TempData["error"] = "Tài khoản đăng nhập không đúng";
                return View();
            }

        }
        //public ActionResult DangXuat()
        //{
        //    Session.Remove("user");
        //    FormsAuthentication.SignOut();
        //    return RedirectToAction("DangNhap");
        //}



        // GET: Hàng_Hóa
        [AdminAuthorize(idChucNang = 2)]
        public ActionResult Index()
        {
            var hàng_Hóa = db.Hàng_Hóa.Include(h => h.ĐVT).Include(h => h.Loại);
            return View(hàng_Hóa.ToList());
        }

        // GET: Hàng_Hóa1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hàng_Hóa hàng_Hóa = db.Hàng_Hóa.Find(id);
            if (hàng_Hóa == null)
            {
                return HttpNotFound();
            }
            return View(hàng_Hóa);
        }


        [AdminAuthorize(idChucNang = 2)]
        // GET: Hàng_Hóa1/Create
        public ActionResult Create()
        {
            ViewBag.ID_DVT = new SelectList(db.ĐVT, "ID", "Tên");
            ViewBag.ID_loại = new SelectList(db.Loại, "ID", "Tên");
            return View();
        }

        // POST: Hàng_Hóa1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthorize(idChucNang = 2)]
        public ActionResult Create([Bind(Include = "ID,Tên,Giá_mua,Giá_bán,ID_loại,ID_DVT,SL_ton,Hinh_anh")] Hàng_Hóa hàng_Hóa)
        {
            if (ModelState.IsValid)
            {
                db.Hàng_Hóa.Add(hàng_Hóa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_DVT = new SelectList(db.ĐVT, "ID", "Tên", hàng_Hóa.ID_DVT);
            ViewBag.ID_loại = new SelectList(db.Loại, "ID", "Tên", hàng_Hóa.ID_loại);
            return View(hàng_Hóa);
        }


        // GET: Hàng_Hóa/Edit/5
        [AdminAuthorize(idChucNang = 2)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hàng_Hóa hàng_Hóa = db.Hàng_Hóa.Find(id);
            if (hàng_Hóa == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_DVT = new SelectList(db.ĐVT, "ID", "Tên", hàng_Hóa.ID_DVT);
            ViewBag.ID_loại = new SelectList(db.Loại, "ID", "Tên", hàng_Hóa.ID_loại);
            return View(hàng_Hóa);
        }

        // POST: Hàng_Hóa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthorize(idChucNang = 2)]
        public ActionResult Edit([Bind(Include = "ID,Tên,Giá_mua,Giá_bán,ID_loại,ID_DVT,SL_ton,Hinh_anh")] Hàng_Hóa hàng_Hóa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hàng_Hóa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_DVT = new SelectList(db.ĐVT, "ID", "Tên", hàng_Hóa.ID_DVT);
            ViewBag.ID_loại = new SelectList(db.Loại, "ID", "Tên", hàng_Hóa.ID_loại);
            return View(hàng_Hóa);
        }

        // GET: Hàng_Hóa/Delete/5
        [AdminAuthorize(idChucNang = 2)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hàng_Hóa hàng_Hóa = db.Hàng_Hóa.Find(id);
            if (hàng_Hóa == null)
            {
                return HttpNotFound();
            }
            return View(hàng_Hóa);
        }


        // POST: Hàng_Hóa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hàng_Hóa hàng_Hóa = db.Hàng_Hóa.Find(id);
            db.Hàng_Hóa.Remove(hàng_Hóa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Quanlyban(string SearchString)
        {
            var Hàng_Hóa = db.Hàng_Hóa.Include(p => p.Loại);
            if (!String.IsNullOrEmpty(SearchString))
            {
                Hàng_Hóa = Hàng_Hóa.Where(s => s.Tên.Contains(SearchString));
            }
            return View(Hàng_Hóa.ToList());
        }
        public ActionResult Proview(string SearchString)
        {
                var Hàng_Hóa = db.Hàng_Hóa.Include(p => p.Loại);
                if (!String.IsNullOrEmpty(SearchString))
                {
                    Hàng_Hóa = Hàng_Hóa.Where(s => s.Tên.Contains(SearchString));
                }
                return View(Hàng_Hóa.ToList());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Hàng_Hóa/Create.cshtml
@model Demo_CNPM.Models.Hàng_Hóa

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Hàng_Hóa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tên, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tên, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tên, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Giá_mua, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Giá_mua, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Giá_mua, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Giá_bán, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Giá_bán, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Giá_bán, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_loại, "ID_loại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_loại", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_loại, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_DVT, "ID_DVT", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_DVT", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_DVT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SL_ton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SL_ton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SL_ton, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hinh_anh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hinh_anh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hinh_anh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Hàng_Hóa/DangNhap.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="vi">
<head>
    <!-- Design by foolishdeveloper.com -->
    <title>Login Form</title>
    <meta charset="utf-8"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
        *,
        *:before,
        *:after {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {
            background-color: #080710;
        }

        .background {
            width: 430px;
            height: 520px;
            position: absolute;
            transform: translate(-50%,-50%);
            left: 50%;
            top: 50%;
        }

            .background .shape {
                height: 200px;
                width: 200px;
                position: absolute;
                border-radius: 50%;
            }

        .shape:first-child {
            background: linear-gradient( #1845ad, #23a2f6 );
            left: -80px;
            top: -80px;
        }

        .shape:last-child {
            background: linear-gradient( to right, #ff512f, #f09819 );
            right: -30px;
            bottom: -80px;
        }

        form {
            height: 520px;
            width: 400px;
            background-color: rgba(255,255,255,0.13);
            position: absolute;
            transform: translate(-50%,-50%);
            top: 50%;
            left: 50%;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 2px solid rgba(255,255,255,0.1);
            box-shadow: 0 0 40px rgba(8,7,16,0.6);
            padding: 50px 35px;
        }

            form * {
                font-family: 'Poppins',sans-serif;
                color: #ffffff;
                letter-spacing: 0.5px;
                outline: none;
                border: none;
            }

            form h3 {
                font-size: 32px;
                font-weight: 500;
                line-height: 42px;
                text-align: center;
            }

        label {
            display: block;
            margin-top: 30px;
            font-size: 16px;
            font-weight: 500;
        }

        input {
            display: block;
            height: 50px;
            width: 100%;
            background-color: rgba(255,255,255,0.07);
            border-radius: 3px;
            padding: 0 10px;
            margin-top: 8px;
            font-size: 14px;
            font-weight: 300;
        }

        ::placeholder {
            color: #e5e5e5;
        }

        button {
            margin-top: 50px;
            width: 100%;
            background-color: #ffffff;
            color: #080710;
            padding: 15px 0;
            font-size: 18px;
            font-weight: 600;
            border-radius: 5px;
            cursor: pointer;
        }

        .social {
            margin-top: 30px;
            display: flex;
        }

            .social div {
                background: red;
                width: 150px;
                border-radius: 3px;
                padding: 5px 10px 10px 5px;
                background-color: rgba(255,255,255,0.27);
                color: #eaf0fb;
                text-align: center;
            }

                .social div:hover {
                    background-color: rgba(255,255,255,0.47);
                }

            .social .fb {
                margin-left: 25px;
            }

            .social i {
                margin-right: 4px;
            }
    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        <h3>Login Here</h3>

        <label for="username">user</label>
        <input type="text" placeholder="Email or Phone" name="user">

        <label for="password">password</label>
        <input type="password" placeholder="Password" name="password">
        <div>
            <p class="text-danger">
                @TempData["error"]
            </p>
        </div>
        <button type="submit">Log In</button>
        <div class="social">
            <div class="go"><i class="fab fa-google"></i>  Google</div>
            <div class="fb"><i class="fab fa-facebook"></i>  Facebook</div>
        </div>
    </form>
</body>
</html>

Views/Hàng_Hóa/DangXuat.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DangXuat</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Views/Hàng_Hóa/Delete.cshtml
@model Demo_CNPM.Models.Hàng_Hóa

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hàng_Hóa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tên)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tên)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Giá_mua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Giá_mua)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Giá_bán)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Giá_bán)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SL_ton)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SL_ton)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh_anh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh_anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ĐVT.Tên)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ĐVT.Tên)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Loại.Tên)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Loại.Tên)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Hàng_Hóa/Details.cshtml
@model Demo_CNPM.Models.Hàng_Hóa

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<style>
    /* Tạo khung viền cho phần chi tiết */
    .dl-horizontal {
        border: 1px solid #ccc;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    /* Tùy chỉnh kiểu chữ cho các phần tử dt và dd */
    dl.dt-horizontal dt,
    dl.dt-horizontal dd {
        display: inline-block;
        margin-right: 10px; /* Khoảng cách giữa cặp dt và dd */
        font-weight: bold;
        color: #333;
    }

    /* Tạo hover effect cho nút Edit */
    .btn-success:hover {
        background-color: #4CAF50;
    }

    /* Tạo hover effect cho nút Back */
    .btn-back:hover {
        background-color: #ccc;
    }
</style>


<h2>Details</h2>
<div>
    <h4>Hàng_Hóa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tên)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tên)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Giá_mua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Giá_mua)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Giá_bán)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Giá_bán)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SL_ton)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SL_ton)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh_anh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh_anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ĐVT.Tên)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ĐVT.Tên)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Loại.Tên)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Loại.Tên)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Hàng_Hóa/Proview.cshtml
@model IEnumerable<Demo_CNPM.Models.Hàng_Hóa>
@{
    ViewBag.Title = "Proview";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<head>
    <style>
        /* ... Các CSS hiện có ... */

        /* CSS cho nút "Tiếp tục mua hàng" */
        .btn-tieptucmuahang {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            text-align: center;
            text-decoration: none;
            background-color: #1E90FF;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        /* Hiệu ứng hover cho nút "Tiếp tục mua hàng" */
        .btn-tieptucmuahang:hover {
            background-color: #007BFF;
        }


        /* CSS cho phần giao diện của thẻ sản phẩm */
        .product-card {
            border: 1px solid #ddd; /* Viền xung quanh thẻ sản phẩm */
            padding: 10px; /* Khoảng cách giữa nội dung và viền */
            background-color: #fff; /* Màu nền của thẻ sản phẩm */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Tạo hiệu ứng đổ bóng */
            transition: box-shadow 0.3s ease; /* Thêm hiệu ứng chuyển đổi mềm mượt */
            margin-bottom: 20px; /* Điều chỉnh khoảng cách giữa các thẻ sản phẩm */
            text-align:center;
        }


        div.vertical-line {
            width: 1px;
            background-color: silver;
            height: 100%;
            float: left;
            border: 2px ridge silver;
            border-radius: 2px;
        }

            /* Hiệu ứng hover cho thẻ sản phẩm */
            .product-card:hover {
                box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2); /* Đổi hiệu ứng đổ bóng khi hover */
            }

        .product-image {
            max-width: 100%;
            max-height: 150px; /* Điều chỉnh kích thước ảnh theo ý muốn */
            object-fit: contain; /* Căn giữa ảnh trong khung */
        }
        /* ... Các CSS hiện có ... */
    </style>
</head>
<body>

    <h2 style="">Quản Lý Bán Hàng</h2>
    <div class="vertical-line" style="height: auto;"></div>

    <div class="container" style=" background-image:; background-repeat: no-repeat; background-size:cover">
        <h2 style="font-size:30px;color:brown;text-align:center"><b>Danh sách hàng hóa</b></h2>
        <div style="border: 3px solid #ff6a00; height: 70px; text-align: center; padding: 15px;; margin-bottom: 50px">

            @using (Html.BeginForm("Proview", "Hàng_Hóa", FormMethod.Get))
            {
                <table>

                    <td>
                        <span style="color:brown"><b> Tên Sản phẩm :</b></span> <input type="text" name="SearchString" />
                        <input type="submit" value="Tìm kiếm" class="btn btn-warning" />
                    </td>
                </table>
            }
        </div>
        <div class="row">
            @foreach (var pro in Model)
            {
                <div class="col-sm-12 col-sm-6 col-md-4 col-lg-3">
                    <div class="product-card">
                        <a href="/ShoppingCart/AddToCart/@pro.ID">
                            <img src="~/images/@pro.Hinh_anh" class="product-image" width="80" height="80" />
                        </a>
                        <p style="font-size:17px;color:darkorchid"><b>@Html.DisplayFor(model => pro.Tên)</b></p>
                        <p>Đơn giá : <font color="red"><i style="font-size:20px">@Html.DisplayFor(model => pro.Giá_bán) VND</i></font></p>
                    </div>
                </div>
            }
        </div>
        <hr />
        <div style="width: auto; height: auto; background-color: #ffa8B6">
            @Html.Action("ShowCart", "ShoppingCart")
        </div>
    </div>
</body>

Views/Hàng_Hóa/Quanlyban.cshtml
@model IEnumerable<Demo_CNPM.Models.Hàng_Hóa>
@{
    ViewBag.Title = "Quanlyban";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<h2>Quản Lý Bán Hàng</h2>

<div class="container" style=" background-image:; background-repeat: no-repeat; background-size:cover">
    <h2 style="font-size:40px;color:brown;text-align:center"><b>MUA HÀNG</b></h2>
    <div style="border: 3px solid #ff6a00; height: 70px; text-align: center; padding: 15px;">

        @using (Html.BeginForm("Quanlyban", "Hàng_Hóa", FormMethod.Get))
        {
            <table>

                <td>
                    <span style="color:brown"><b> Tên Sản phẩm :</b></span> <input type="text" name="SearchString" />
                    <input type="submit" value="Tìm kiếm" class="btn btn-warning" />
                </td>
            </table>

        }
    </div>
    <style>
    </style>
    <div class="row">
        @foreach (var pro in Model)
        {
            <div class="col-sm-12 col-sm-6 col-md-4 col-lg-3">
                <div class="card-pro">

                    <img src="~/images/@pro.Hinh_anh" width="200" height="250" />
                    <p style="font-size:17px;color:darkorchid"><b>@Html.DisplayFor(model => pro.Tên)</b></p>
                    <p>Đơn giá : <font color="red"><i style="font-size:20px">@Html.DisplayFor(model => pro.Giá_bán)</i></font></p>
                    <p>Số lượng tồn  : <font color="red"><i style="font-size:20px">@Html.DisplayFor(model => pro.SL_ton)</i></font></p>
                    <p>Loại  : <font color="red"><i style="font-size:20px">@Html.DisplayFor(model => pro.ID_loại)</i></font></p>
                    <p style="text-align: center;">
                        @Html.ActionLink("Details", "Details", new { id = pro.ID }, new { @class = "btn btn-primary" }) |
                        <a href="/ShoppingCart/AddToCart/@pro.ID" class="btn btn-danger"> Mua </a>
                    </p>
                </div>
            </div>
        }
    </div>
</div>