Models/Chi_tiết_hóa_đơn.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_tiết_hóa_đơn
    {
        public int ID { get; set; }
        public Nullable<int> ID_HH { get; set; }
        public Nullable<int> ID_HD { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<int> Đơn_giá { get; set; }
        public Nullable<int> Thành_tiền { get; set; }
    
        public virtual Hóa_đơn Hóa_đơn { get; set; }
        public virtual Hàng_Hóa Hàng_Hóa { get; set; }

    }
}

Controllers/Chi_tiết_hóa_đơnController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Demo_CNPM.App_Start;
using Demo_CNPM.Models;

namespace Demo_CNPM.Controllers
{
    public class Chi_tiết_hóa_đơnController : Controller
    {
        private taphoa_final_demoEntities4 db = new taphoa_final_demoEntities4();

        // GET: Chi_tiết_hóa_đơn
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Index()
        {
            var chi_tiết_hóa_đơn = db.Chi_tiết_hóa_đơn.Include(c => c.Hóa_đơn).Include(c => c.Hàng_Hóa);
            return View(chi_tiết_hóa_đơn.ToList());
        }

        // GET: Chi_tiết_hóa_đơn/Details/5
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Details(int? id)
        {
           
            Chi_tiết_hóa_đơn chi_tiết_hóa_đơn = db.Chi_tiết_hóa_đơn.FirstOrDefault(hd => hd.ID_HD == id);
            if (chi_tiết_hóa_đơn == null)
            {
                return HttpNotFound();
            }
            return View(chi_tiết_hóa_đơn);
        }

        // GET: Chi_tiết_hóa_đơn/Create
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Create()
        {
            ViewBag.ID_HD = new SelectList(db.Hóa_đơn, "ID", "ID_NV");
            ViewBag.ID_HH = new SelectList(db.Hàng_Hóa, "ID", "Tên");
            return View();
        }

        // POST: Chi_tiết_hóa_đơn/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Create([Bind(Include = "ID_HH,ID_HD,SL,Đơn_giá,Thành_tiền")] Chi_tiết_hóa_đơn chi_tiết_hóa_đơn)
        {
            if (ModelState.IsValid)
            {
                db.Chi_tiết_hóa_đơn.Add(chi_tiết_hóa_đơn);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_HD = new SelectList(db.Hóa_đơn, "ID", "ID_NV", chi_tiết_hóa_đơn.ID_HD);
            ViewBag.ID_HH = new SelectList(db.Hàng_Hóa, "ID", "Tên", chi_tiết_hóa_đơn.ID_HH);
            return View(chi_tiết_hóa_đơn);
        }

        // GET: Chi_tiết_hóa_đơn/Edit/5
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chi_tiết_hóa_đơn chi_tiết_hóa_đơn = db.Chi_tiết_hóa_đơn.Find(id);
            if (chi_tiết_hóa_đơn == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_HD = new SelectList(db.Hóa_đơn, "ID", "ID_NV", chi_tiết_hóa_đơn.ID_HD);
            ViewBag.ID_HH = new SelectList(db.Hàng_Hóa, "ID", "Tên", chi_tiết_hóa_đơn.ID_HH);
            return View(chi_tiết_hóa_đơn);
        }

        // POST: Chi_tiết_hóa_đơn/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Edit([Bind(Include = "ID_HH,ID_HD,SL,Đơn_giá,Thành_tiền")] Chi_tiết_hóa_đơn chi_tiết_hóa_đơn)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chi_tiết_hóa_đơn).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_HD = new SelectList(db.Hóa_đơn, "ID", "ID_NV", chi_tiết_hóa_đơn.ID_HD);
            ViewBag.ID_HH = new SelectList(db.Hàng_Hóa, "ID", "Tên", chi_tiết_hóa_đơn.ID_HH);
            return View(chi_tiết_hóa_đơn);
        }

        // GET: Chi_tiết_hóa_đơn/Delete/5
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chi_tiết_hóa_đơn chi_tiết_hóa_đơn = db.Chi_tiết_hóa_đơn.Find(id);
            if (chi_tiết_hóa_đơn == null)
            {
                return HttpNotFound();
            }
            return View(chi_tiết_hóa_đơn);
        }

        // POST: Chi_tiết_hóa_đơn/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult DeleteConfirmed(int? id)
        {
            Chi_tiết_hóa_đơn chi_tiết_hóa_đơn = db.Chi_tiết_hóa_đơn.Find(id);
            db.Chi_tiết_hóa_đơn.Remove(chi_tiết_hóa_đơn);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/Hóa_đơnController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Demo_CNPM.Models;
using Demo_CNPM.App_Start;

namespace Demo_CNPM.Controllers
{
    public class Hóa_đơnController : Controller
    {
        private taphoa_final_demoEntities4 db = new taphoa_final_demoEntities4();

        // GET: Hóa_đơn
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Index()
        {
            var hóa_đơn = db.Hóa_đơn.Include(h => h.Nhân_viên);
            return View(hóa_đơn.ToList());
        }

        // GET: Hóa_đơn/Details/5
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hóa_đơn hóa_đơn = db.Hóa_đơn.Find(id);
            if (hóa_đơn == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Details", "Chi_tiết_hóa_đơn", new { id = id });
        }

        // GET: Hóa_đơn/Create
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Create()
        {
            ViewBag.ID_NV = new SelectList(db.Nhân_viên, "ID", "Tên");
            return View();
        }

        // POST: Hóa_đơn/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Create([Bind(Include = "ID,ID_NV,Ngày_bán,Tổng_SL,Tổng_tiền")] Hóa_đơn hóa_đơn)
        {
            if (ModelState.IsValid)
            {
                db.Hóa_đơn.Add(hóa_đơn);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_NV = new SelectList(db.Nhân_viên, "ID", "Tên", hóa_đơn.ID_NV);
            return View(hóa_đơn);
        }

        // GET: Hóa_đơn/Edit/5
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hóa_đơn hóa_đơn = db.Hóa_đơn.Find(id);
            if (hóa_đơn == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_NV = new SelectList(db.Nhân_viên, "ID", "Tên", hóa_đơn.ID_NV);
            return View(hóa_đơn);
        }

        // POST: Hóa_đơn/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Edit([Bind(Include = "ID,ID_NV,Ngày_bán,Tổng_SL,Tổng_tiền")] Hóa_đơn hóa_đơn)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hóa_đơn).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_NV = new SelectList(db.Nhân_viên, "ID", "Tên", hóa_đơn.ID_NV);
            return View(hóa_đơn);
        }

        // GET: Hóa_đơn/Delete/5
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hóa_đơn hóa_đơn = db.Hóa_đơn.Find(id);
            if (hóa_đơn == null)
            {
                return HttpNotFound();
            }
            return View(hóa_đơn);
        }

        // POST: Hóa_đơn/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult DeleteConfirmed(int? id)
        {
            Hóa_đơn hóa_đơn = db.Hóa_đơn.Find(id);
            if (hóa_đơn == null)
            {
                return HttpNotFound();
            }
            // Lấy danh sách các bản ghi Chi_tiết_hóa_đơn có liên quan đến Hóa_đơn
            var chiTiets = db.Chi_tiết_hóa_đơn.Where(ct => ct.ID_HD == id).ToList();

            // Xóa các bản ghi Chi_tiết_hóa_đơn liên quan
            foreach (var chiTiet in chiTiets)
            {
                db.Chi_tiết_hóa_đơn.Remove(chiTiet);
            }
            db.Hóa_đơn.Remove(hóa_đơn);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Chi_tiết_hóa_đơn/Create.cshtml
@model Demo_CNPM.Models.Chi_tiết_hóa_đơn

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chi_tiết_hóa_đơn</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_HH, "ID_HH", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_HH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_HH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_HD, "ID_HD", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_HD", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_HD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Đơn_giá, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Đơn_giá, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Đơn_giá, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thành_tiền, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thành_tiền, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thành_tiền, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Chi_tiết_hóa_đơn/Delete.cshtml
@model Demo_CNPM.Models.Chi_tiết_hóa_đơn

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Chi_tiết_hóa_đơn</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Đơn_giá)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Đơn_giá)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thành_tiền)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thành_tiền)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hóa_đơn.ID_NV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hóa_đơn.ID_NV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hàng_Hóa.Tên)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hàng_Hóa.Tên)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Chi_tiết_hóa_đơn/Details.cshtml
@model Demo_CNPM.Models.Chi_tiết_hóa_đơn

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<h2>Details</h2>
<style>
    /* Tạo khung viền cho phần chi tiết */
    .dl-horizontal {
        border: 1px solid #ccc;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    /* Tùy chỉnh kiểu chữ cho các phần tử dt và dd */
    dl.dt-horizontal dt,
    dl.dt-horizontal dd {
        display: inline-block;
        margin-right: 10px; /* Khoảng cách giữa cặp dt và dd */
        font-weight: bold;
        color: #333;
    }

    /* Tạo hover effect cho nút Edit */
    .btn-success:hover {
        background-color: #4CAF50;
    }

    /* Tạo hover effect cho nút Back */
    .btn-back:hover {
        background-color: #ccc;
    }
</style>

<div>
    <h4>Chi_tiết_hóa_đơn</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Đơn_giá)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Đơn_giá)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thành_tiền)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thành_tiền)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hóa_đơn.ID_NV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hóa_đơn.ID_NV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hàng_Hóa.Tên)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hàng_Hóa.Tên)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { @class = "btn btn-success" }) |
    @Html.ActionLink("Back to List", "Index","Hóa_đơn")
</p>

Views/Chi_tiết_hóa_đơn/Edit.cshtml
@model Demo_CNPM.Models.Chi_tiết_hóa_đơn

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chi_tiết_hóa_đơn</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_HH)

        @Html.HiddenFor(model => model.ID_HD)

        <div class="form-group">
            @Html.LabelFor(model => model.SL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Đơn_giá, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Đơn_giá, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Đơn_giá, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thành_tiền, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thành_tiền, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thành_tiền, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Chi_tiết_hóa_đơn/Index.cshtml
@model IEnumerable<Demo_CNPM.Models.Chi_tiết_hóa_đơn>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Đơn_giá)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Thành_tiền)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hóa_đơn.ID_NV)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hàng_Hóa.Tên)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Đơn_giá)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Thành_tiền)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hóa_đơn.ID_NV)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hàng_Hóa.Tên)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>